// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgPGyzqVusrCOXGPKUrDq3hdkp6fetiQM',
    appId: '1:1057555079617:web:d077b4a173109694870f40',
    messagingSenderId: '1057555079617',
    projectId: 'kids-learning-from-flashcards',
    authDomain: 'kids-learning-from-flashcards.firebaseapp.com',
    storageBucket: 'kids-learning-from-flashcards.firebasestorage.app',
    measurementId: 'G-ZNECELMYSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9H44SDQN5XGEdfUIM_nMK-0r88r7Hd08',
    appId: '1:1057555079617:android:3447e67ddf0c0e1a870f40',
    messagingSenderId: '1057555079617',
    projectId: 'kids-learning-from-flashcards',
    storageBucket: 'kids-learning-from-flashcards.firebasestorage.app',
  );
}
